{
  "version": 3,
  "file": "_map_errors.js",
  "sourceRoot": "..",
  "sources": [
    "src/_map_errors.coffee"
  ],
  "names": [],
  "mappings": ";AAM4C;EAAA;;;;;;EAE5C;;;;;;;;;;;;;;;;;;;;;;;AAF4C",
  "sourcesContent": [
    "\n### This is the original `pull-stream/throughs/map` implementation with the `try`/`catch` clause removed so\nall errors are thrown. This, until we find out how to properly handle errors the pull-streams way. Note\nthat `_map_errors` behaves exactly like `pull-stream/throughs/filter` which tells me this shouldn't be\ntoo wrong. Also observe that while any library may require all errors to be given to a callback or\nsomesuch, no library can really enforce that because not all client code may be wrapped, so I think\nwe're stuck with throwing errors anyway. ###\n\n```\nvar prop = require('pull-stream/util/prop')\n\nmodule.exports = this._map_errors = function (mapper) {\n  if(!mapper) return return_id\n  mapper = prop(mapper)\n  return function (read) {\n    return function (abort, cb) {\n      read(abort, function (end, data) {\n        // try {\n        data = !end ? mapper(data) : null\n        // } catch (err) {\n        //   return read(err, function () {\n        //     return cb(err)\n        //   })\n        // }\n        cb(end, data)\n      })\n    }\n  }\n}\n```\n"
  ]
}